# src/mapping/finger_ids.py
WRIST = 0
THUMB_TIP, INDEX_TIP, MIDDLE_TIP, RING_TIP, PINKY_TIP = 4, 8, 12, 16, 20
TIP_TO_NAME = {4:"Thumb", 8:"Index", 12:"Middle", 16:"Ring", 20:"Pinky"}
RIGHT_PLAY_ORDER = [THUMB_TIP, INDEX_TIP, MIDDLE_TIP, RING_TIP, PINKY_TIP]
LEFT_PLAY_ORDER  = [THUMB_TIP, INDEX_TIP, MIDDLE_TIP, RING_TIP, PINKY_TIP]
TIP_TO_PIP = {4:3, 8:6, 12:10, 16:14, 20:18}